# Site settings
title: drush.io - documentation
description: > # this means to ignore newlines until "baseurl:"
    Training guides and documentation for drush.io, the distributed runtime
    utility shell.
url: "https://help.drush.io"
baseurl: "/"
logo: <img src="/assets/img/logo-64.png" alt="drush.io" class="logo" /> drush.io
paginate: 5
paginate_path: "/page:num/"
owner:
    #email: support@drush.io
    facebook:
        show: false
        name: "Ichihara Rifa"
        url: "https://fb.me/profile-id-here"
    github:
        show: true
        username: "drush-io"
    twitter:
        show: true
        username: "drush_io"
    disqus:
        show: false
        username: "disqus-id-here"
    linkedin:
        show: false
        profile: "https://linkedin.com/in/your-profile-id-here"
sass:
    sass_dir: _sass
    style: compressed
permalink: "/:title"
highlighter: rouge
exclude:
  - 'node_modules'
